### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 0bie** [0bie/uiComponents#1]
- [ ] Unit Tests
- [ ] Responsive Tests
- [x] Support asset and JSON loading
- [ ] Refactor components to support data
- [ ] Build more components...
